export const TREATMENTS = [
  {
    num: "01",
    name: "The Stone Ritual",
    cat: "Body · Restorative",
    duration: "90 min",
    price: "KES 18,000",
    desc: "Heated basalt and Kenyan riverstone, laid in slow procession along the spine. The body releases what it has been quietly carrying — sometimes for years.",
  },
  {
    num: "02",
    name: "Desert Bloom Facial",
    cat: "Face · Luminance",
    duration: "60 min",
    price: "KES 14,000",
    desc: "Cold-pressed argan, Damask rose otto and a long, considered gua sha sequence. The skin emerges lit from beneath — never tight, never pulled.",
  },
  {
    num: "03",
    name: "The Silence Session",
    cat: "Mind · Stillness",
    duration: "45 min",
    price: "KES 9,500",
    desc: "Guided breath, slow scalp work, weighted darkness across the eyes. Reserved for the mind that has not paused in months. Often, the most asked-for hour.",
  },
  {
    num: "04",
    name: "Deep Argan Ritual",
    cat: "Body · Release",
    duration: "75 min",
    price: "KES 16,000",
    desc: "Warmed argan and a deliberate, deep-tissue cadence. Long unhurried strokes that follow the architecture of the body rather than fight it.",
  },
  {
    num: "05",
    name: "Himalayan Salt Detox",
    cat: "Body · Renewal",
    duration: "60 min",
    price: "KES 13,500",
    desc: "Mineral salt scrub, herbal wrap and a soft rinse beneath low light. The body emerges quieter, lighter — fully resurfaced.",
  },
  {
    num: "06",
    name: "Gold Gua Sha Lift",
    cat: "Face · Sculpt",
    duration: "50 min",
    price: "KES 12,000",
    desc: "Sculpting facial work with 24k gold tools. Lymphatic drainage, contour and a soft, lasting glow. A favourite before evenings that matter.",
  },
];
